insert into base_prices (category, price) values ('cat', 10);
insert into base_prices (category, price) values ('bird', 20);
insert into base_prices (category, price) values ('dog', 10);
insert into base_prices (category, price) values ('fish', 15);
insert into base_prices (category, price) values ('guinea pig', 20);
insert into base_prices (category, price) values ('hamster', 10);
insert into base_prices (category, price) values ('ferret', 14);
insert into base_prices (category, price) values ('turtle', 12);
insert into base_prices (category, price) values ('horse', 40);
insert into base_prices (category, price) values ('snake', 15);
insert into base_prices (category, price) values ('husky', 15);
insert into base_prices (category, price) values ('golden retriever', 15);
insert into base_prices (category, price) values ('rabbit', 18);
insert into base_prices (category, price) values ('bat', 17);
insert into base_prices (category, price) values ('otter', 30);
insert into base_prices (category, price) values ('buffalo', 30);
insert into base_prices (category, price) values ('bunny', 15);
insert into base_prices (category, price) values ('budgie', 15);
insert into base_prices (category, price) values ('gecko', 20);
insert into base_prices (category, price) values ('chinchilla', 15);
insert into base_prices (category, price) values ('parakeet', 20);
insert into base_prices (category, price) values ('gerbil', 17);
insert into base_prices (category, price) values ('lovebird', 15);
insert into base_prices (category, price) values ('cockatiel', 16);
insert into base_prices (category, price) values ('finch', 15);
insert into base_prices (category, price) values ('rat', 30);
insert into base_prices (category, price) values ('quail', 18);
insert into base_prices (category, price) values ('gerbil', 18);
insert into base_prices (category, price) values ('green anole', 14);
insert into base_prices (category, price) values ('chicken', 20);