insert into pets (poname, pname, profile, category, special_requirements) values ('lcarriage2g', 'alan', 'cute kitty cat', 'cat', 'can only be bathed on mondays');
insert into pets (poname, pname, profile, category, special_requirements) values ('lcarriage2g', 'bobby', null, 'chinchilla', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('atrickey2h', 'calista', null, 'cat', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('clacasa2i', 'danny', null, 'turtle', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('clacasa2i', 'ellie', null, 'snake', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('aberge2j', 'fred', null, 'horse', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('mtomkiss2k', 'gabriel', null, 'snake', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('nfollis2l', 'harry', null, 'turtle', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('mmcgrowther2m', 'indigo', null, 'horse', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('atripney2n', 'julien', null, 'chinchilla', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('amclucas2o', 'kelly', 'small and thin snake', 'snake', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('bsuttle2p', 'lewis', 'cute fluffy rabbit', 'rabbit', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('pcalbreath2q', 'moony', null, 'chinchilla', 'needs to be petted at least 3 times a day');
insert into pets (poname, pname, profile, category, special_requirements) values ('mpetruska2r', 'ned', null, 'turtle', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('mpetruska2r', 'oliver', null, 'rabbit', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('dbodemeaid2s', 'pooja', null, 'snake', 'needs to be around at least one other snake at all times');
insert into pets (poname, pname, profile, category, special_requirements) values ('kfrancisco2t', 'qenny', null, 'horse', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('lsteggals2u', 'rudy', null, 'snake', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('bollive2v', 'luna', null, 'turtle', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('bollive2v', 'zed', null, 'husky', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('nsparks2w', 'kendra', null, 'husky', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('kbleesing2x', 'cecilion', null, 'cat', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('rpetry2y', 'milo', null, 'chinchilla', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('squaife2z', 'horlick', null, 'turtle', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('dlamb30', 'greenie', null, 'rabbit', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('nallchorn31', 'tuktuk', null, 'husky', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('khazelgrove32', 'wenny', null, 'husky', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('lmercey3x', 'fani', null, 'horse', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('ksellor3y', 'logi', null, 'cockatiel', null);
insert into pets (poname, pname, profile, category, special_requirements) values ('tbeyne3z', 'thor', null, 'golden retriever', null);